module.exports = {
  "Navy": "Navy Midshipmen",
  "ND": "Notre Dame Fighting Irish",
  "Jacksonville St": "Jacksonville State Gamecocks",
  "Hawaii": "TBD",
  "Ohio": "TBD",
  "Mass": "Massachusetts Minutemen",
  "UMass": "Massachusetts Minutemen",
  "New Mex St": "New Mexico State Aggies",
  "Vandy": "Vanderbilt Commodores",
  "USC": "USC Trojans",
  "FIU": "Florida International Panthers",
  "LA Tech": "Louisiana Tech Bulldogs",
  "Texas Tech": "Texas Tech Red Raiders",
  "Florida": "TBD",
  "Tulsa": "Tulsa Golden Hurricane",
  "Nebraska": "Nebraska Cornhuskers",
  "Mich St": "Michigan State Spartans",
  "Mich St.": "Michigan State Spartans",
  "Mich State": "Michigan State Spartans",
  "Michigan State": "Michigan State Spartans",
  "Miami FL": "Miami Hurricanes",
  "Iowa": "TBD",
  "Utah St": "Utah State Aggies",
  "Utah St.": "Utah State Aggies",
  "Ohio St": "Ohio State Buckeyes",
  "Ohio St.": "Ohio State Buckeyes",
  "Indiana": "TBD",
  "South Car": "South Carolina Gamecocks",
  "Coastal Car": "Coastal Carolina Chanticleers",
  "Northwestern": "Utah Utes",
  "San Jose St": "San José State Spartans",
  "San Jose State": "San José State Spartans",
  "SJSU": "San José State Spartans",
  "FSU": "Florida State Seminoles",
  "Florida St": "Florida State Seminoles",
  "Florida St.": "Florida State Seminoles",
  "Duke": "TBD",
  "Indiana St": "Indiana State Sycamores",
  "Illinois": "Akron Zips",
  "Kansas": "TBD",
  "Army": "Army Black Knights",
  "Wake Forest": "Wake Forest Demon Deacons",
  "SMU": "SMU Mustangs",
  "Texas": "TBD",
  "North Car St": "NC State Wolfpack",
  "North Car St.": "NC State Wolfpack",
  "Tulane": "Tulane Green Wave",
  "Washington St": "Washington State Cougars",
  "Washington St.": "Washington State Cougars",
  "Wash State": "Washington State Cougars",
  "Standford": "Stanford Cardinal",
  "Stanford": "Stanford Cardinal",
  "Baylor": "Baylor Bears",
  "North Car": "North Carolina Tar Heels",
  "North Carolina": "Troy Trojans",
  "Maryland": "Maryland Terrapins",
  "Temple": "Temple Owls",
  "LSU": "LSU Tigers",
  "Tenn": "Tennessee Volunteers",
  "Tennessee": "TBD",
  "Arkansas": "Akron Zips",
  "Purdue": "Purdue Boilermakers",
  "Colorado": "TBD",
  "Troy": "Troy Trojans",
  "Wisconsin": "Wisconsin Badgers",
  "Wisco": "Wisconsin Badgers",
  "Air Force": "Air Force Falcons",
  "Clemson": "Clemson Tigers",
  "Mich": "Michigan Wolverines",
  "Michigan": "Rice Owls",
  "Rutgers": "Rutgers Scarlet Knights",
  "Bama": "Alabama Crimson Tide",
  "Alabama": "TBD",
  "Alabam": "Alabama Crimson Tide",
  "Utah": "TBD",
  "Iowa St": "Iowa State Cyclones",
  "Iowa St.": "Iowa State Cyclones",
  "Iowa State": "Iowa State Cyclones",
  "Oregon St": "Oregon State Beavers",
  "Oregon St.": "Oregon State Beavers",
  "Louisville": "Louisville Cardinals",
  "UConn": "UConn Huskies",
  "BYU": "BYU Cougars",
  "Buffalo": "Buffalo Bulls",
  "Ole Miss": "Ole Miss Rebels",
  "Oklahoma": "TBD",
  "Syracuse": "Syracuse Orange",
  "Arizona": "Akron Zips",
  "Miss St": "Mississippi State Bulldogs",
  "Miss St.": "Mississippi State Bulldogs",
  "Elon": "Elon Phoenix",
  "Arizona St": "Arizona State Sun Devils",
  "Arizona St.": "Arizona State Sun Devils",
  "Texas A&M": "Texas A&M Aggies",
  "Georgia": "TBD",
  "Colorado St": "Colorado State Rams",
  "Colorado St.": "Colorado State Rams",
  "UCLA": "UCLA Bruins",
  "Kansas St": "Kansas State Wildcats",
  "Kansas St.": "Kansas State Wildcats",
  "Ok St": "Oklahoma State Cowboys",
  "Ok St.": "Oklahoma State Cowboys",
  "OK St": "Oklahoma State Cowboys",
  "OSU": "Ohio State Buckeyes",
  "Houston": "TBD",
  "Washington": "Utah Utes",
  "Wash": "Washington Huskies",
  "Memphis": "Memphis Tigers",
  "Cinci": "Cincinnati Bearcats",
  "Cincinnati": "Cincinnati Bearcats",
  "TCU": "TCU Horned Frogs",
  "South Florida": "South Florida Bulls",
  "Auburn": "Auburn Tigers",
  "Georgia St": "Georgia State Panthers",
  "Georgia St.": "Georgia Bulldogs",
  "Boise St": "Boise State Broncos",
  "Boise": "Boise State Broncos",
  "Penn St": "Penn State Nittany Lions",
  "Penn St.": "Penn State Nittany Lions",
  "Penn State": "Penn State Nittany Lions",
  "Ball St": "Ball State Cardinals",
  "Ball St.": "Ball State Cardinals",
  "Miami(OH)": "Miami (OH) RedHawks",
  "Miami (OH)": "Miami (OH) RedHawks",
  "Miami Ohio": "Miami (OH) RedHawks",
  "ASU": "Arizona State Sun Devils",
  "Oregon": "Oregon Ducks",
  "Western Mich": "Western Michigan Broncos",
  "Weetern Mich": "Western Michigan Broncos",
  "Western Michigan": "Western Michigan Broncos",
  "JMU": "TBD",
  "Kentucky": "Oregon Ducks",
  "Rice": "Rice Owls",
  "Toledo": "Toledo Rockets",
  "Boston College": "Boston College Eagles",
  "Boston Colleg": "Boston College Eagles",
  "NW": "Northwestern Wildcats",
  "Mizz": "Missouri Tigers",
  "Missouri": "Missouri Tigers",
  "Cincy": "Cincinnati Bearcats",
  "UNC": "North Carolina Tar Heels",
  "Wyoming": "Wyoming Cowboys",
  "South Alabama": "South Alabama Jaguars",
  "Northern Illinois": "Northern Illinois Huskies",
  "NIU": "Northern Illinois Huskies",
  "Georgia Tech": "Georgia Tech Yellow Jackets",
  "California": "California Golden Bears",
  "Cal": "TBD",
  "Virginia Tech": "Virginia Tech Hokies",
  "Virginia Tech.": "Virginia Tech Hokies",
  "VaTech": "Virginia Tech Hokies",
  "Texas St": "Texas State Bobcats",
  "Texas St.": "Utah Utes",
  "Montana": "TBD",
  "San Diego St": "San Diego State Aztecs",
  "San Diego St.": "San Diego State Aztecs",
  "Liberty": "Liberty Flames",
  "Coastal Carolina": "Coastal Carolina Chanticleers",
  "UTSA": "UTSA Roadrunners",
  "Western Kentucky": "Western Kentucky Hilltoppers",
  "Louisiana Lafay": "Louisiana Ragin' Cajuns",
  "New Mexico St": "New Mexico State Aggies",
  "Minn": "Minnesota Golden Gophers",
  "Minnesota": "VMI Keydets",
  "Bowling Green": "Bowling Green Falcons",
  "UNLV": "UNLV Rebels",
  "UTEP": "UTEP Miners",
  "Akron": "Akron Zips",
  "Indiana State": "Indiana State Sycamores",
  "Illinois State": "Illinois State Redbirds",
  "Missouri State": "Missouri Tigers",
  "North Dakota State": "North Dakota State Bison",
  "South Dakota State": "South Dakota State Jackrabbits",
  "Sacramento State": "Sacramento State Hornets",
  "Delaware State": "Delaware State Hornets",
  "Hampton": "Hampton Pirates",
  "Delaware": "UCLA Bruins",
  "UC Davis": "UC Davis Aggies",
  "Northern Colorado": "Northern Colorado Bears",
  "Eastern Washington": "Eastern Washington Eagles",
  "Weber State": "Weber State Wildcats",
  "Cal Poly": "Cal Poly Mustangs",
  "Idaho State": "Idaho State Bengals",
  "Idaho": "TBD",
  "Southern Utah": "Southern Utah Thunderbirds",
  "Utah Tech": "Utah Tech Trailblazers",
  "Kennesaw State": "Kennesaw State Owls",
  "Tusculum": "Tusculum Pioneers",
  "Nevada": "Nevada Wolf Pack",
  "Long Island University": "Long Island University Sharks",
  "Sam Houston": "Sam Houston Bearkats",
  "Gardner-Webb": "Gardner-Webb Runnin' Bulldogs",
  "Appalachian State": "Appalachian State Mountaineers",
  "Charlotte": "Charlotte 49ers",
  "Eastern Kentucky": "Eastern Kentucky Colonels",
  "Howard": "Howard Bison",
  "Eastern Michigan": "Eastern Michigan Eagles",
  "Monmouth": "Monmouth Hawks",
  "Georgia Southern": "Georgia Southern Eagles",
  "The Citadel": "The Citadel Bulldogs",
  "Rhode Island": "Rhode Island Rams",
  "UT Martin": "UT Martin Skyhawks",
  "Bethune-Cookman": "Bethune-Cookman Wildcats",
  "Central Michigan": "Central Michigan Chippewas",
  "SE Louisiana": "SE Louisiana Lions",
  "South Dakota": "South Dakota Coyotes",
  "Nicholls": "Nicholls Colonels",
  "Robert Morris": "Robert Morris Colonials",
  "Middle Tennessee": "Middle Tennessee Blue Raiders",
  "Florida Atlantic": "Florida Atlantic Owls",
  "UAB": "UAB Blazers",
  "Old Dominion": "Old Dominion Monarchs",
  "Villanova": "Villanova Wildcats",
  "Sacred Heart": "Sacred Heart Pioneers",
  "Abilene Christian": "Abilene Christian Wildcats",
  "Chattanooga": "Chattanooga Mocs",
  "New Mexico": "New Mexico Lobos",
  "Fresno State": "Fresno State Bulldogs",
  "San José State": "San José State Spartans",
  "Georgia State": "Georgia State Panthers",
  "Boise State": "Boise State Broncos",
  "Jacksonville State": "Jacksonville State Gamecocks",
  "Louisiana Lafayette": "Louisiana Ragin' Cajuns"
};